OpenLayers.Util.OSM={};OpenLayers.Util.OSM.MISSING_TILE_URL="http://www.freemap.co.il/images/expand.gif";OpenLayers.Util.OSM.originalOnImageLoadError=OpenLayers.Util.onImageLoadError;OpenLayers.Util.onImageLoadError=function(){if(this.src.match(/^http:\/\/tiles[123]\.waze\.com\//)){this.src=OpenLayers.Util.OSM.MISSING_TILE_URL;}else{OpenLayers.Util.OSM.originalOnImageLoadError;}};OpenLayers.Layer.OSM=OpenLayers.Class(OpenLayers.Layer.TMS,{initialize:function(name,url,options){options=OpenLayers.Util.extend({attribution:"Data by <a href='http://www.waze.com/'>Waze.com</a>",maxExtent:new OpenLayers.Bounds(-20037508.34,-20037508.34,20037508.34,20037508.34),resolutions:[78271.51695,39135.758475,19567.8792375,9783.93961875,4891.969809375,2445.984904687,1222.992452343,611.496226172,305.748113086,152.874056543,76.437028271,38.218514136,19.109257068,9.554628534,4.777314267,2.388657133],maxResolution:78271.51695,units:"m",projection:"EPSG:900913",transitionEffect:"resize"},options);var newArguments=[name,url,options];OpenLayers.Layer.TMS.prototype.initialize.apply(this,newArguments);},api_token:"",getURL:function(bounds){var res=this.map.getResolution();var x=Math.round((bounds.left-this.maxExtent.left)/(res*this.tileSize.w));var y=Math.round((this.maxExtent.top-bounds.top)/(res*this.tileSize.h));var z=this.map.getZoom()+1;var limit=Math.pow(2,z);if(y<0||y>=limit)
{return OpenLayers.Util.OSM.MISSING_TILE_URL;}
else
{x=((x%limit)+limit)%limit;var url=this.url;var path="tiles/"+z+"/"+x+"/"+y+".png";if(this.api_token&&this.api_token.length>0)
path+="?api_token="+this.api_token;if(url instanceof Array)
{url=this.selectUrl(path,url);}
return url+path;}},CLASS_NAME:"OpenLayers.Layer.OSM"});OpenLayers.Layer.OSM.Mapnik=OpenLayers.Class(OpenLayers.Layer.OSM,{initialize:function(name,options){var url=["http://tiles1.waze.com/","http://tiles2.waze.com/","http://tiles3.waze.com/","http://tiles4.waze.com/"];options=OpenLayers.Util.extend({numZoomLevels:10},options);var newArguments=[name,url,options];OpenLayers.Layer.OSM.prototype.initialize.apply(this,newArguments);},CLASS_NAME:"OpenLayers.Layer.OSM.Mapnik"});
OpenLayers.Control.WazePanZoomBar=OpenLayers.Class(OpenLayers.Control.PanZoomBar,{zoomStopWidth:37,zoomStopHeight:10,initialize:function(){OpenLayers.Control.PanZoomBar.prototype.initialize.apply(this,arguments);},draw:function(px){OpenLayers.Control.prototype.draw.apply(this,arguments);px=this.position.clone();this.buttons=[];var sz=new OpenLayers.Size(37,42);var zoom_bar_sz=new OpenLayers.Size(37,104);this._addButton("zoomin","zoom-plus-mini.png",px,sz);var centered=this._addZoomBar(px.add(0,sz.h));this._addButton("zoomout","zoom-minus-mini.png",centered,sz);return this.div;},_addZoomBar:function(centered){var imgLocation=OpenLayers.Util.getImagesLocation();var id=this.id+"_"+this.map.id;var zoomsToEnd=this.map.getNumZoomLevels()-1-this.map.getZoom();var slider=OpenLayers.Util.createAlphaImageDiv(id,centered.add(14,zoomsToEnd*this.zoomStopHeight),new OpenLayers.Size(9,10),imgLocation+"slider.png","absolute");this.slider=slider;this.sliderEvents=new OpenLayers.Events(this,slider,null,true,{includeXY:true});this.sliderEvents.on({"mousedown":this.zoomBarDown,"mousemove":this.zoomBarDrag,"mouseup":this.zoomBarUp,"dblclick":this.doubleClick,"click":this.doubleClick});var sz=new OpenLayers.Size();sz.h=this.zoomStopHeight*this.map.getNumZoomLevels();sz.w=this.zoomStopWidth;var div=null;if(OpenLayers.Util.alphaHack()){var id=this.id+"_"+this.map.id;div=OpenLayers.Util.createAlphaImageDiv(id,centered,new OpenLayers.Size(sz.w,this.zoomStopHeight),imgLocation+"zoombar.png","absolute",null,"crop");div.style.height=sz.h+"px";}else{div=OpenLayers.Util.createDiv('OpenLayers_Control_PanZoomBar_Zoombar'+this.map.id,centered,sz,imgLocation+"zoombar.png");}
this.zoombarDiv=div;this.divEvents=new OpenLayers.Events(this,div,null,true,{includeXY:true});this.divEvents.on({"mousedown":this.divClick,"mousemove":this.passEventToSlider,"dblclick":this.doubleClick,"click":this.doubleClick});this.div.appendChild(div);this.startTop=parseInt(div.style.top);this.div.appendChild(slider);this.map.events.register("zoomend",this,this.moveZoomBar);centered=centered.add(0,this.zoomStopHeight*this.map.getNumZoomLevels());return centered;},CLASS_NAME:"OpenLayers.Control.WazePanZoomBar"});
var g_waze_server="http://www.waze.com"
if(typeof(g_waze_config.locale)!="undefined"&&g_waze_config.locale=="israel")
g_waze_server="http://www.waze.co.il";function WazeEmbeddedMap(map_info,div,center_lon,center_lat,zoom,api_token){this.map_info=map_info;OpenLayers.IMAGE_RELOAD_ATTEMPTS=3;var bounds=new OpenLayers.Bounds();bounds.extend(new OpenLayers.LonLat(map_info.left,map_info.top));bounds.extend(new OpenLayers.LonLat(map_info.right,map_info.bottom));this.map=new OpenLayers.Map('map',{controls:[new OpenLayers.Control.Navigation()/*,new OpenLayers.Control.WazePanZoomBar(),new OpenLayers.Control.Scale(),new OpenLayers.Control.Permalink(null,base=g_waze_server+"/livemap"),new OpenLayers.Control.MousePosition()*/],maxResolution:.010986328125,maxExtent:bounds,numZoomLevels:11,zoom:zoom});if(map_info.base_layer_type=="WMS"){var base_layer='base';var map_servers=["http://ymap1.waze.co.il/wms-c/","http://212.150.51.86/wms-c/"];var layer=new OpenLayers.Layer.WMS("Base Layer",map_servers,{layers:base_layer,format:'image/png'},{transitionEffect:"resize",buffer:1});layer.mergeNewParams({"api_token":api_token});this.map.addLayer(layer);}
if(map_info.base_layer_type=="OSM"){var layer=new OpenLayers.Layer.OSM.Mapnik("Base Layer",{displayOutsideMaxExtent:true,wrapDateLine:true});layer["api_token"]=api_token;this.map.addLayer(layer);}
this.map.setCenter(lonlat=new OpenLayers.LonLat(lon=center_lon,lat=center_lat),zoom=zoom);jQuery(".olControlPermalink a").css({"display":"block","width":"104px","height":"33px","margin":"6px","background-image":"url("+g_waze_server+"/images/transparent_logo.png)"});jQuery(".olControlPermalink a").attr("target","_blank");jQuery(".olControlPermalink a").text("");jQuery(".olControlPermalink").css({"top":"0px","right":"0px","bottom":"auto","margin-top":"0px","margin-right":"0px"});var has_border=jQuery("#map").css("border");if(!has_border||has_border.length==0)
jQuery("#map").css("border","1px solid #aaa");}
function deleteJSONP(){var script;while(script=document.getElementById('WAZE_JSONP')){script.parentNode.removeChild(script);for(var prop in script)
try{delete script[prop];}
catch(err){}}}
function waze_map_info_callback(map_info){g_waze_map=new WazeEmbeddedMap(map_info,g_waze_config.div_id,g_waze_config.center_lon,g_waze_config.center_lat,g_waze_config.zoom,g_waze_config.token);if(g_waze_config.framed_cloud_image_url&&g_waze_config.framed_cloud_image_url.length>0){OpenLayers.Popup.FramedCloud.prototype.initialize=function(id,lonlat,contentSize,contentHTML,anchor,closeBox,closeBoxCallback){this.imageSrc=g_waze_config.framed_cloud_image_url;OpenLayers.Popup.Framed.prototype.initialize.apply(this,arguments);this.contentDiv.className=this.contentDisplayClass;}}
g_waze_map.find=function(term,callback_name,ignore_location){var params={q:term,token:g_waze_config.token,ts:(new Date()).getTime()};var location=g_waze_map.map.getCenter();if(g_waze_map.map.getProjection()=="EPSG:900913")
location.transform(g_waze_map.map.getProjectionObject(),new OpenLayers.Projection("EPSG:4326"));if(!ignore_location){params.lon=location.lon;params.lat=location.lat;}
params.callback=callback_name;setTimeout(function(){deleteJSONP();var find_script=document.createElement("script");find_script.src=g_waze_server+"/WAS/mozi?"+$.param(params);find_script.type="text/javascript";find_script.charset="UTF-8";find_script.id="WAZE_JSONP";document.body.appendChild(find_script);},0);}
if(typeof(onWazeMapInit)=="function")
onWazeMapInit();else if(typeof(g_waze_config.callback)=="function")
g_waze_config.callback();}
jQuery().ready(function(){g_waze_map_init=function(){OpenLayers._getScriptLocation=function(){return g_waze_server+"/js/";}
deleteJSONP();var map_info=document.createElement("script");map_info.src=g_waze_server+"/WAS/map_info?callback=waze_map_info_callback";map_info.type="text/javascript";map_info.id="WAZE_JSONP";document.body.appendChild(map_info);}
if(typeof(g_waze_config.init_on_page_load)=="boolean"&&!g_waze_config.init_on_page_load)
return;g_waze_map_init();});
